/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.qms.parser.antlr.internal.InternalQmsParser;
import org.xtext.example.qms.services.QmsGrammarAccess;

public class QmsParser extends AbstractAntlrParser {

	@Inject
	private QmsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQmsParser createParser(XtextTokenStream stream) {
		return new InternalQmsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public QmsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QmsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
