/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQmsScopeProvider extends DelegatingScopeProvider {
}
