/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.qms.ui.AbstractQmsUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class QmsUiModule extends AbstractQmsUiModule {
  public QmsUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
