/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bom Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.qms.qms.BomNode#getWeight <em>Weight</em>}</li>
 *   <li>{@link org.xtext.example.qms.qms.BomNode#getChildren <em>Children</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.qms.qms.QmsPackage#getBomNode()
 * @model
 * @generated
 */
public interface BomNode extends RepositoryNode
{
  /**
   * Returns the value of the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' attribute.
   * @see #setWeight(int)
   * @see org.xtext.example.qms.qms.QmsPackage#getBomNode_Weight()
   * @model
   * @generated
   */
  int getWeight();

  /**
   * Sets the value of the '{@link org.xtext.example.qms.qms.BomNode#getWeight <em>Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' attribute.
   * @see #getWeight()
   * @generated
   */
  void setWeight(int value);

  /**
   * Returns the value of the '<em><b>Children</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.qms.qms.BomNode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Children</em>' containment reference list.
   * @see org.xtext.example.qms.qms.QmsPackage#getBomNode_Children()
   * @model containment="true"
   * @generated
   */
  EList<BomNode> getChildren();

} // BomNode
