/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Evidence Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.qms.qms.EvidenceNode#getChildren <em>Children</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.qms.qms.QmsPackage#getEvidenceNode()
 * @model
 * @generated
 */
public interface EvidenceNode extends RepositoryNode
{
  /**
   * Returns the value of the '<em><b>Children</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.qms.qms.EvidenceNode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Children</em>' containment reference list.
   * @see org.xtext.example.qms.qms.QmsPackage#getEvidenceNode_Children()
   * @model containment="true"
   * @generated
   */
  EList<EvidenceNode> getChildren();

} // EvidenceNode
