/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.qms.qms.NodeReference#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.qms.qms.QmsPackage#getNodeReference()
 * @model
 * @generated
 */
public interface NodeReference extends NodeBodyElement
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(RepositoryNode)
   * @see org.xtext.example.qms.qms.QmsPackage#getNodeReference_Ref()
   * @model
   * @generated
   */
  RepositoryNode getRef();

  /**
   * Sets the value of the '{@link org.xtext.example.qms.qms.NodeReference#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(RepositoryNode value);

} // NodeReference
