/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Body Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.qms.qms.QmsPackage#getNodeBodyElement()
 * @model
 * @generated
 */
public interface NodeBodyElement extends EObject
{
} // NodeBodyElement
