/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.qms.qms.QmsFactory
 * @model kind="package"
 * @generated
 */
public interface QmsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "qms";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/qms/Qms";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "qms";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QmsPackage eINSTANCE = org.xtext.example.qms.qms.impl.QmsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.ModelImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.RepositoryImpl <em>Repository</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.RepositoryImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getRepository()
   * @generated
   */
  int REPOSITORY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY__NAME = MODEL__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY__TYPE = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Root</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY__ROOT = MODEL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Repository</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_FEATURE_COUNT = MODEL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.RepositoryNodeImpl <em>Repository Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.RepositoryNodeImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getRepositoryNode()
   * @generated
   */
  int REPOSITORY_NODE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_NODE__NAME = MODEL__NAME;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_NODE__TITLE = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_NODE__BODY = MODEL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Repository Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_NODE_FEATURE_COUNT = MODEL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.RequirementNodeImpl <em>Requirement Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.RequirementNodeImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getRequirementNode()
   * @generated
   */
  int REQUIREMENT_NODE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_NODE__NAME = REPOSITORY_NODE__NAME;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_NODE__TITLE = REPOSITORY_NODE__TITLE;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_NODE__BODY = REPOSITORY_NODE__BODY;

  /**
   * The feature id for the '<em><b>Former Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_NODE__FORMER_NAME = REPOSITORY_NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Children</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_NODE__CHILDREN = REPOSITORY_NODE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Requirement Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_NODE_FEATURE_COUNT = REPOSITORY_NODE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.BomNodeImpl <em>Bom Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.BomNodeImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getBomNode()
   * @generated
   */
  int BOM_NODE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOM_NODE__NAME = REPOSITORY_NODE__NAME;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOM_NODE__TITLE = REPOSITORY_NODE__TITLE;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOM_NODE__BODY = REPOSITORY_NODE__BODY;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOM_NODE__WEIGHT = REPOSITORY_NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Children</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOM_NODE__CHILDREN = REPOSITORY_NODE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bom Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOM_NODE_FEATURE_COUNT = REPOSITORY_NODE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.EvidenceNodeImpl <em>Evidence Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.EvidenceNodeImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getEvidenceNode()
   * @generated
   */
  int EVIDENCE_NODE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVIDENCE_NODE__NAME = REPOSITORY_NODE__NAME;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVIDENCE_NODE__TITLE = REPOSITORY_NODE__TITLE;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVIDENCE_NODE__BODY = REPOSITORY_NODE__BODY;

  /**
   * The feature id for the '<em><b>Children</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVIDENCE_NODE__CHILDREN = REPOSITORY_NODE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Evidence Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVIDENCE_NODE_FEATURE_COUNT = REPOSITORY_NODE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.NodeBodyElementImpl <em>Node Body Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.NodeBodyElementImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getNodeBodyElement()
   * @generated
   */
  int NODE_BODY_ELEMENT = 6;

  /**
   * The number of structural features of the '<em>Node Body Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_BODY_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.TextImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getText()
   * @generated
   */
  int TEXT = 7;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__TEXT = NODE_BODY_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = NODE_BODY_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.impl.NodeReferenceImpl <em>Node Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.impl.NodeReferenceImpl
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getNodeReference()
   * @generated
   */
  int NODE_REFERENCE = 8;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_REFERENCE__REF = NODE_BODY_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Node Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_REFERENCE_FEATURE_COUNT = NODE_BODY_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.qms.qms.RepositoryType <em>Repository Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.qms.qms.RepositoryType
   * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getRepositoryType()
   * @generated
   */
  int REPOSITORY_TYPE = 9;


  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.qms.qms.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.qms.qms.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.qms.qms.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.Repository <em>Repository</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Repository</em>'.
   * @see org.xtext.example.qms.qms.Repository
   * @generated
   */
  EClass getRepository();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.qms.qms.Repository#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.qms.qms.Repository#getType()
   * @see #getRepository()
   * @generated
   */
  EAttribute getRepository_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.qms.qms.Repository#getRoot <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Root</em>'.
   * @see org.xtext.example.qms.qms.Repository#getRoot()
   * @see #getRepository()
   * @generated
   */
  EReference getRepository_Root();

  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.RepositoryNode <em>Repository Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Repository Node</em>'.
   * @see org.xtext.example.qms.qms.RepositoryNode
   * @generated
   */
  EClass getRepositoryNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.qms.qms.RepositoryNode#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.example.qms.qms.RepositoryNode#getTitle()
   * @see #getRepositoryNode()
   * @generated
   */
  EAttribute getRepositoryNode_Title();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.qms.qms.RepositoryNode#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.example.qms.qms.RepositoryNode#getBody()
   * @see #getRepositoryNode()
   * @generated
   */
  EReference getRepositoryNode_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.RequirementNode <em>Requirement Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Requirement Node</em>'.
   * @see org.xtext.example.qms.qms.RequirementNode
   * @generated
   */
  EClass getRequirementNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.qms.qms.RequirementNode#getFormerName <em>Former Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Former Name</em>'.
   * @see org.xtext.example.qms.qms.RequirementNode#getFormerName()
   * @see #getRequirementNode()
   * @generated
   */
  EAttribute getRequirementNode_FormerName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.qms.qms.RequirementNode#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Children</em>'.
   * @see org.xtext.example.qms.qms.RequirementNode#getChildren()
   * @see #getRequirementNode()
   * @generated
   */
  EReference getRequirementNode_Children();

  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.BomNode <em>Bom Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bom Node</em>'.
   * @see org.xtext.example.qms.qms.BomNode
   * @generated
   */
  EClass getBomNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.qms.qms.BomNode#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight</em>'.
   * @see org.xtext.example.qms.qms.BomNode#getWeight()
   * @see #getBomNode()
   * @generated
   */
  EAttribute getBomNode_Weight();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.qms.qms.BomNode#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Children</em>'.
   * @see org.xtext.example.qms.qms.BomNode#getChildren()
   * @see #getBomNode()
   * @generated
   */
  EReference getBomNode_Children();

  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.EvidenceNode <em>Evidence Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evidence Node</em>'.
   * @see org.xtext.example.qms.qms.EvidenceNode
   * @generated
   */
  EClass getEvidenceNode();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.qms.qms.EvidenceNode#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Children</em>'.
   * @see org.xtext.example.qms.qms.EvidenceNode#getChildren()
   * @see #getEvidenceNode()
   * @generated
   */
  EReference getEvidenceNode_Children();

  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.NodeBodyElement <em>Node Body Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Body Element</em>'.
   * @see org.xtext.example.qms.qms.NodeBodyElement
   * @generated
   */
  EClass getNodeBodyElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.xtext.example.qms.qms.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.qms.qms.Text#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.qms.qms.Text#getText()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.qms.qms.NodeReference <em>Node Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Reference</em>'.
   * @see org.xtext.example.qms.qms.NodeReference
   * @generated
   */
  EClass getNodeReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.qms.qms.NodeReference#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.example.qms.qms.NodeReference#getRef()
   * @see #getNodeReference()
   * @generated
   */
  EReference getNodeReference_Ref();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.qms.qms.RepositoryType <em>Repository Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Repository Type</em>'.
   * @see org.xtext.example.qms.qms.RepositoryType
   * @generated
   */
  EEnum getRepositoryType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QmsFactory getQmsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.ModelImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.RepositoryImpl <em>Repository</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.RepositoryImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getRepository()
     * @generated
     */
    EClass REPOSITORY = eINSTANCE.getRepository();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REPOSITORY__TYPE = eINSTANCE.getRepository_Type();

    /**
     * The meta object literal for the '<em><b>Root</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPOSITORY__ROOT = eINSTANCE.getRepository_Root();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.RepositoryNodeImpl <em>Repository Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.RepositoryNodeImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getRepositoryNode()
     * @generated
     */
    EClass REPOSITORY_NODE = eINSTANCE.getRepositoryNode();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REPOSITORY_NODE__TITLE = eINSTANCE.getRepositoryNode_Title();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPOSITORY_NODE__BODY = eINSTANCE.getRepositoryNode_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.RequirementNodeImpl <em>Requirement Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.RequirementNodeImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getRequirementNode()
     * @generated
     */
    EClass REQUIREMENT_NODE = eINSTANCE.getRequirementNode();

    /**
     * The meta object literal for the '<em><b>Former Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REQUIREMENT_NODE__FORMER_NAME = eINSTANCE.getRequirementNode_FormerName();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENT_NODE__CHILDREN = eINSTANCE.getRequirementNode_Children();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.BomNodeImpl <em>Bom Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.BomNodeImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getBomNode()
     * @generated
     */
    EClass BOM_NODE = eINSTANCE.getBomNode();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOM_NODE__WEIGHT = eINSTANCE.getBomNode_Weight();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOM_NODE__CHILDREN = eINSTANCE.getBomNode_Children();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.EvidenceNodeImpl <em>Evidence Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.EvidenceNodeImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getEvidenceNode()
     * @generated
     */
    EClass EVIDENCE_NODE = eINSTANCE.getEvidenceNode();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVIDENCE_NODE__CHILDREN = eINSTANCE.getEvidenceNode_Children();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.NodeBodyElementImpl <em>Node Body Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.NodeBodyElementImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getNodeBodyElement()
     * @generated
     */
    EClass NODE_BODY_ELEMENT = eINSTANCE.getNodeBodyElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.TextImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__TEXT = eINSTANCE.getText_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.impl.NodeReferenceImpl <em>Node Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.impl.NodeReferenceImpl
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getNodeReference()
     * @generated
     */
    EClass NODE_REFERENCE = eINSTANCE.getNodeReference();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_REFERENCE__REF = eINSTANCE.getNodeReference_Ref();

    /**
     * The meta object literal for the '{@link org.xtext.example.qms.qms.RepositoryType <em>Repository Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.qms.qms.RepositoryType
     * @see org.xtext.example.qms.qms.impl.QmsPackageImpl#getRepositoryType()
     * @generated
     */
    EEnum REPOSITORY_TYPE = eINSTANCE.getRepositoryType();

  }

} //QmsPackage
