/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repository</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.qms.qms.Repository#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.qms.qms.Repository#getRoot <em>Root</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.qms.qms.QmsPackage#getRepository()
 * @model
 * @generated
 */
public interface Repository extends Model
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.qms.qms.RepositoryType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.qms.qms.RepositoryType
   * @see #setType(RepositoryType)
   * @see org.xtext.example.qms.qms.QmsPackage#getRepository_Type()
   * @model
   * @generated
   */
  RepositoryType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.qms.qms.Repository#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.qms.qms.RepositoryType
   * @see #getType()
   * @generated
   */
  void setType(RepositoryType value);

  /**
   * Returns the value of the '<em><b>Root</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Root</em>' containment reference.
   * @see #setRoot(RepositoryNode)
   * @see org.xtext.example.qms.qms.QmsPackage#getRepository_Root()
   * @model containment="true"
   * @generated
   */
  RepositoryNode getRoot();

  /**
   * Sets the value of the '{@link org.xtext.example.qms.qms.Repository#getRoot <em>Root</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Root</em>' containment reference.
   * @see #getRoot()
   * @generated
   */
  void setRoot(RepositoryNode value);

} // Repository
