/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repository Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.qms.qms.RepositoryNode#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.qms.qms.RepositoryNode#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.qms.qms.QmsPackage#getRepositoryNode()
 * @model
 * @generated
 */
public interface RepositoryNode extends Model
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.example.qms.qms.QmsPackage#getRepositoryNode_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.qms.qms.RepositoryNode#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.qms.qms.NodeBodyElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference list.
   * @see org.xtext.example.qms.qms.QmsPackage#getRepositoryNode_Body()
   * @model containment="true"
   * @generated
   */
  EList<NodeBodyElement> getBody();

} // RepositoryNode
