/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class QmsUiModule extends AbstractQmsUiModule {
}
