/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.ide;

import org.xtext.example.qms.ide.AbstractQmsIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class QmsIdeModule extends AbstractQmsIdeModule {
}
