/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.qms.QmsRuntimeModule;
import org.xtext.example.qms.QmsStandaloneSetup;
import org.xtext.example.qms.ide.QmsIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class QmsIdeSetup extends QmsStandaloneSetup {
  @Override
  public Injector createInjector() {
    QmsRuntimeModule _qmsRuntimeModule = new QmsRuntimeModule();
    QmsIdeModule _qmsIdeModule = new QmsIdeModule();
    return Guice.createInjector(Modules2.mixin(_qmsRuntimeModule, _qmsIdeModule));
  }
}
