/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.qms.ui.internal.QmsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QmsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(QmsActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		QmsActivator activator = QmsActivator.getInstance();
		return activator != null ? activator.getInjector(QmsActivator.ORG_XTEXT_EXAMPLE_QMS_QMS) : null;
	}

}
