/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.qms.QmsRuntimeModule
import org.xtext.example.qms.QmsStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class QmsIdeSetup extends QmsStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new QmsRuntimeModule, new QmsIdeModule))
	}
	
}
