/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class QmsStandaloneSetup extends QmsStandaloneSetupGenerated {

	def static void doSetup() {
		new QmsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
