/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.qms.qms.NodeBodyElement;
import org.xtext.example.qms.qms.QmsPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Node Body Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NodeBodyElementImpl extends MinimalEObjectImpl.Container implements NodeBodyElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NodeBodyElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QmsPackage.Literals.NODE_BODY_ELEMENT;
  }

} //NodeBodyElementImpl
