/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms.qms.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.qms.qms.QmsPackage;
import org.xtext.example.qms.qms.RequirementNode;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Requirement Node</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.qms.qms.impl.RequirementNodeImpl#getFormerName <em>Former Name</em>}</li>
 *   <li>{@link org.xtext.example.qms.qms.impl.RequirementNodeImpl#getChildren <em>Children</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RequirementNodeImpl extends RepositoryNodeImpl implements RequirementNode
{
  /**
   * The default value of the '{@link #getFormerName() <em>Former Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFormerName()
   * @generated
   * @ordered
   */
  protected static final String FORMER_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFormerName() <em>Former Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFormerName()
   * @generated
   * @ordered
   */
  protected String formerName = FORMER_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getChildren() <em>Children</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChildren()
   * @generated
   * @ordered
   */
  protected EList<RequirementNode> children;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RequirementNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QmsPackage.Literals.REQUIREMENT_NODE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFormerName()
  {
    return formerName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFormerName(String newFormerName)
  {
    String oldFormerName = formerName;
    formerName = newFormerName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QmsPackage.REQUIREMENT_NODE__FORMER_NAME, oldFormerName, formerName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<RequirementNode> getChildren()
  {
    if (children == null)
    {
      children = new EObjectContainmentEList<RequirementNode>(RequirementNode.class, this, QmsPackage.REQUIREMENT_NODE__CHILDREN);
    }
    return children;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QmsPackage.REQUIREMENT_NODE__CHILDREN:
        return ((InternalEList<?>)getChildren()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QmsPackage.REQUIREMENT_NODE__FORMER_NAME:
        return getFormerName();
      case QmsPackage.REQUIREMENT_NODE__CHILDREN:
        return getChildren();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QmsPackage.REQUIREMENT_NODE__FORMER_NAME:
        setFormerName((String)newValue);
        return;
      case QmsPackage.REQUIREMENT_NODE__CHILDREN:
        getChildren().clear();
        getChildren().addAll((Collection<? extends RequirementNode>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QmsPackage.REQUIREMENT_NODE__FORMER_NAME:
        setFormerName(FORMER_NAME_EDEFAULT);
        return;
      case QmsPackage.REQUIREMENT_NODE__CHILDREN:
        getChildren().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QmsPackage.REQUIREMENT_NODE__FORMER_NAME:
        return FORMER_NAME_EDEFAULT == null ? formerName != null : !FORMER_NAME_EDEFAULT.equals(formerName);
      case QmsPackage.REQUIREMENT_NODE__CHILDREN:
        return children != null && !children.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (formerName: ");
    result.append(formerName);
    result.append(')');
    return result.toString();
  }

} //RequirementNodeImpl
