/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.qms;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.xtext.example.qms.AbstractQmsRuntimeModule;
import org.xtext.example.qms.indexing.QmsDeclarativeQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class QmsRuntimeModule extends AbstractQmsRuntimeModule {
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return QmsDeclarativeQualifiedNameProvider.class;
  }
}
